// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"time"
)

type Order struct {
	ID           int64     `json:"id"`
	Code         int32     `json:"code"`
	CustomerCode int32     `json:"customer_code"`
	TotalValue   string    `json:"total_value"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type OrderItem struct {
	ID        int64     `json:"id"`
	OrderID   int64     `json:"order_id"`
	Product   string    `json:"product"`
	Quantity  int32     `json:"quantity"`
	Price     string    `json:"price"`
	CreatedAt time.Time `json:"created_at"`
}
