// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: orders.sql

package database

import (
	"context"
)

const countOrdersByCustomer = `-- name: CountOrdersByCustomer :one
SELECT COUNT(*) FROM orders
WHERE customer_code = $1
`

func (q *Queries) CountOrdersByCustomer(ctx context.Context, customerCode int32) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOrdersByCustomer, customerCode)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (code, customer_code, total_value, created_at, updated_at)
VALUES ($1, $2, $3, NOW(), NOW())
RETURNING id, code, customer_code, total_value, created_at, updated_at
`

type CreateOrderParams struct {
	Code         int32  `json:"code"`
	CustomerCode int32  `json:"customer_code"`
	TotalValue   string `json:"total_value"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, createOrder, arg.Code, arg.CustomerCode, arg.TotalValue)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.CustomerCode,
		&i.TotalValue,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO order_items (order_id, product, quantity, price, created_at)
VALUES ($1, $2, $3, $4, NOW())
RETURNING id, order_id, product, quantity, price, created_at
`

type CreateOrderItemParams struct {
	OrderID  int64  `json:"order_id"`
	Product  string `json:"product"`
	Quantity int32  `json:"quantity"`
	Price    string `json:"price"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRowContext(ctx, createOrderItem,
		arg.OrderID,
		arg.Product,
		arg.Quantity,
		arg.Price,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Product,
		&i.Quantity,
		&i.Price,
		&i.CreatedAt,
	)
	return i, err
}

const getOrderByCode = `-- name: GetOrderByCode :one
SELECT id, code, customer_code, total_value, created_at, updated_at FROM orders
WHERE code = $1
`

func (q *Queries) GetOrderByCode(ctx context.Context, code int32) (Order, error) {
	row := q.db.QueryRowContext(ctx, getOrderByCode, code)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.CustomerCode,
		&i.TotalValue,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT id, code, customer_code, total_value, created_at, updated_at FROM orders
WHERE id = $1
`

func (q *Queries) GetOrderByID(ctx context.Context, id int64) (Order, error) {
	row := q.db.QueryRowContext(ctx, getOrderByID, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.CustomerCode,
		&i.TotalValue,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderItems = `-- name: GetOrderItems :many
SELECT id, order_id, product, quantity, price, created_at FROM order_items
WHERE order_id = $1
`

func (q *Queries) GetOrderItems(ctx context.Context, orderID int64) ([]OrderItem, error) {
	rows, err := q.db.QueryContext(ctx, getOrderItems, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderItem{}
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.Product,
			&i.Quantity,
			&i.Price,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrdersByCustomerCode = `-- name: GetOrdersByCustomerCode :many
SELECT id, code, customer_code, total_value, created_at, updated_at FROM orders
WHERE customer_code = $1
ORDER BY created_at DESC
`

func (q *Queries) GetOrdersByCustomerCode(ctx context.Context, customerCode int32) ([]Order, error) {
	rows, err := q.db.QueryContext(ctx, getOrdersByCustomerCode, customerCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.CustomerCode,
			&i.TotalValue,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTotalByOrderCode = `-- name: GetTotalByOrderCode :one
SELECT total_value FROM orders
WHERE code = $1
`

func (q *Queries) GetTotalByOrderCode(ctx context.Context, code int32) (string, error) {
	row := q.db.QueryRowContext(ctx, getTotalByOrderCode, code)
	var total_value string
	err := row.Scan(&total_value)
	return total_value, err
}
