// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"context"
)

type Querier interface {
	CountOrdersByCustomer(ctx context.Context, customerCode int32) (int64, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error)
	GetOrderByCode(ctx context.Context, code int32) (Order, error)
	GetOrderByID(ctx context.Context, id int64) (Order, error)
	GetOrderItems(ctx context.Context, orderID int64) ([]OrderItem, error)
	GetOrdersByCustomerCode(ctx context.Context, customerCode int32) ([]Order, error)
	GetTotalByOrderCode(ctx context.Context, code int32) (string, error)
}

var _ Querier = (*Queries)(nil)
